name: video_translator
description: A platform that translate youtube videos to arabic
publish_to: 'none'
# --------------------------------------------------------------------------------
version: 1.0.9
# INSTRUCTIONS WHEN CHANGING APP VERSION
# -> change in ios/runner/info.pList : ( CFBundleVersion )
# -> change in main.dart : ( videoTranslatorAppVersion )
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ---------------------------
  # flutter packages
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  firebase_core: ^2.4.1
  flutter_youtube_downloader: ^0.0.5
  google_sign_in: ^5.4.4
  googleapis: ^10.0.0
  http: ^0.13.4
  image_picker: ^0.8.6+1
  just_audio: ^0.9.31
  page_transition: ^2.0.4
  text_to_speech: ^0.2.3
  translator: ^0.1.7
  video_player: ^2.2.10
  webview_flutter: ^4.0.2
  youtube_player_flutter: ^8.1.2
  # ---------------------------
  # MY WIDGETS
  super_image:
    git:
      url: https://github.com/RagehAz/super_image.git
  super_text:
    git:
      url: https://github.com/RagehAz/super_text.git
  super_box:
    git:
      url: https://github.com/RagehAz/super_box.git
  widget_fader:
    git:
      url: https://github.com/RagehAz/widget_fader.git
  bubbles:
    git:
      url: https://github.com/RagehAz/bubbles.git
  layouts:
    git:
      url: https://github.com/RagehAz/layouts.git
  # ---------------------------
  # MY BACKEND PACKAGES
  rest:
    git:
      url: https://github.com/RagehAz/rest.git
  ldb:
    git:
      url: https://github.com/RagehAz/ldb.git
  # ---------------------------
  # HELPERS
  bldrs_theme:
    git:
      url: https://github.com/RagehAz/bldrs_theme.git
  scale:
    git:
      url: https://github.com/RagehAz/scale.git
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git
  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git
  stringer:
    git:
      url: https://github.com/RagehAz/stringer.git
  filers:
    git:
      url: https://github.com/RagehAz/filers.git
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
#  assets:
#    - assets/
#    - assets/aw/
#    - assets/icons/
#    - assets/icons/keywords/
#    - assets/icons/specs/
#    - assets/icons/flags/
#    - assets/languages/
#    - assets/planet/
#    - assets/sounds/
  # ------------------------------------
  fonts:
    - family: BldrsHeadlineFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_Thin.ttf
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Light.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf
# --------------------------------------------------------------------------------
