name: video_translator
description: A platform that translate youtube videos to arabic
publish_to: 'none'
version: 1.0.2
environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.2.10
  youtube_player_flutter: ^8.1.2
  page_transition: ^2.0.4

  super_image:
    git:
      url: https://github.com/RagehAz/super_image.git
  super_text:
    git:
      url: https://github.com/RagehAz/super_text.git
  super_box:
    git:
      url: https://github.com/RagehAz/super_box.git
  rest:
    git:
      url: https://github.com/RagehAz/rest.git
  ldb:
    git:
      url: https://github.com/RagehAz/ldb.git
  bldrs_theme:
    git:
      url: https://github.com/RagehAz/bldrs_theme.git
  scale:
    git:
      url: https://github.com/RagehAz/scale.git
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git
  widget_fader:
    git:
      url: https://github.com/RagehAz/widget_fader.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0

# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
#  assets:
#    - assets/
#    - assets/aw/
#    - assets/icons/
#    - assets/icons/keywords/
#    - assets/icons/specs/
#    - assets/icons/flags/
#    - assets/languages/
#    - assets/planet/
#    - assets/sounds/
  # ------------------------------------
  fonts:
    - family: BldrsHeadlineFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_Thin.ttf
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Light.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf
# --------------------------------------------------------------------------------
